# Generated by Django 5.2 on 2025-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acciones', 'Acciones'), ('bonos', 'Bonos'), ('fondos', 'Fondos de inversión'), ('criptomonedas', 'Criptomonedas')], max_length=20, unique=True)),
                ('rentabilidad_esperada', models.FloatField(help_text='Ej: 0.08 para 8% anual')),
                ('volatilidad', models.FloatField(help_text='Ej: 0.12 para 12%')),
                ('comision', models.FloatField(help_text='Ej: 0.015 para 1.5%')),
                ('capitalizacion', models.CharField(default='mensual', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_activo', models.CharField(choices=[('acciones', 'Acciones'), ('bonos', 'Bonos'), ('fondos', 'Fondos de inversión'), ('criptomonedas', 'Criptomonedas')], max_length=20)),
                ('plazo_anos', models.PositiveIntegerField()),
                ('reinvertir', models.BooleanField(default=True)),
                ('fecha_simulacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
