# Generated by Django 5.2 on 2025-04-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulacion',
            old_name='plazo_anos',
            new_name='plazo',
        ),
    ]
