# Generated by Django 5.2 on 2025-04-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_rename_plazo_anos_simulacion_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='unidad_tiempo',
            field=models.CharField(choices=[('dias', 'Días'), ('meses', 'Meses'), ('años', 'Años')], default='meses', max_length=10),
        ),
    ]
