# Generated by Django 5.2 on 2025-04-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0003_simulacion_unidad_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionactivo',
            name='capitalizacion',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='fecha_simulacion',
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='comision',
            field=models.FloatField(help_text='Comisión sobre el capital total, en decimal'),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='rentabilidad_esperada',
            field=models.FloatField(help_text='En decimal, por ejemplo 0.08 para 8% anual'),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='tipo',
            field=models.CharField(choices=[('bonos', 'Bonos'), ('acciones', 'Acciones'), ('fondos', 'Fondos Mutuos')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='volatilidad',
            field=models.FloatField(help_text='Desviación estándar anual en decimal'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='monto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='plazo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='reinvertir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='tipo_activo',
            field=models.CharField(choices=[('bonos', 'Bonos'), ('acciones', 'Acciones'), ('fondos', 'Fondos Mutuos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='unidad_tiempo',
            field=models.CharField(choices=[('años', 'Años'), ('meses', 'Meses')], max_length=10),
        ),
    ]
