# Generated by Django 5.2 on 2025-05-07 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0004_remove_configuracionactivo_capitalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionactivo',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, help_text='Nombre descriptivo del tipo de inversión', max_length=100),
            preserve_default=False,
        ),
    ]
