# Generated by Django 5.2 on 2025-05-07 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0005_configuracionactivo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionactivo',
            name='comision',
            field=models.FloatField(help_text='Comisión sobre el capital total, en decimal', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.2)]),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='rentabilidad_esperada',
            field=models.FloatField(help_text='En decimal, por ejemplo 0.08 para 8% anual', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='tipo',
            field=models.CharField(choices=[('bonos', 'Bonos'), ('acciones', 'Acciones'), ('fondos', 'Fondos Mutuos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracionactivo',
            name='volatilidad',
            field=models.FloatField(help_text='Desviación estándar anual en decimal', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
