# Generated by Django 5.2 on 2025-04-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('interes_anual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('seguro', models.DecimalField(decimal_places=2, help_text='Seguro mensual fijo', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('metodo_pago', models.CharField(choices=[('FRANCES', 'Francés'), ('ALEMAN', 'Alemán')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipocredito')),
            ],
        ),
    ]
