# Generated by Django 5.2 on 2025-04-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulacion',
            old_name='creado_en',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='plazo_meses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipocredito',
            name='seguro',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
