# Generated by Django 5.2 on 2025-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_creado_en_simulacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='cuota_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='total_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='metodo_pago',
            field=models.CharField(choices=[('FRANCES', 'Francés'), ('ALEMAN', 'Alemán')], max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='plazo_meses',
            field=models.PositiveIntegerField(),
        ),
    ]
