# Generated by Django 5.2 on 2025-05-05 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_simulacion_cuota_simulacion_cuota_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocredito',
            name='tipo',
            field=models.CharField(choices=[('Productivo Corporativo', 'Productivo Corporativo'), ('Productivo Empresarial', 'Productivo Empresarial'), ('Productivo PYMES', 'Productivo PYMES'), ('Consumo', 'Consumo'), ('Educativo', 'Educativo'), ('Educativo Social', 'Educativo Social'), ('Vivienda de Interés Público', 'Vivienda de Interés Público'), ('Vivienda de Interés Social', 'Vivienda de Interés Social'), ('Inmobiliario', 'Inmobiliario'), ('Microcrédito Minorista', 'Microcrédito Minorista'), ('Microcrédito de Acumulación Simple', 'Microcrédito de Acumulación Simple'), ('Microcrédito de Acumulación Ampliada', 'Microcrédito de Acumulación Ampliada'), ('Inversión Pública', 'Inversión Pública')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
